sudo: false

language: go

go:
  - tip

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover

script:
  - go test -race -covermode=count -coverprofile=coverage.out -v ./.
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci
